version: '3.9'
services:
  wordpress:
    image: 'wordpress:6.2'
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: aldim
      WORDPRESS_DB_NAME: smam
    ports:
      - 1298:80
    restart: always
  db:
    image: 'mariadb:10.11'
    environment:
      - MARIADB_ROOT_PASSWORD=aldim
      - MARIADB_DATABASE=smam
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MARIADB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
